[package]
name = "mock"
version = "1.0.0"
authors = []

[addresses]
mock="0x36e30e32c62d6c3ff4e3f000885626e18d6deb162a8091ac3af6aad4f3bdfae5"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "6f83bc6d02207298b2dee91133d75538789bf582"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
