[package]
name = "mock"
version = "1.0.0"
authors = []

[addresses]
mock="0xfa78899981b78f231628501583779f99565b49cbec9bbf84f9a04465ba17ca55"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "6f83bc6d02207298b2dee91133d75538789bf582"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
