[package]
name = "mock"
version = "1.0.0"
authors = []

[addresses]
mock="0x938dd1008f738a4e85adbdae7a370665604531d19df2851c89311473404cd378"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "6f83bc6d02207298b2dee91133d75538789bf582"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
