[package]
name = "perpetual"
version = "0.0.1"
authors = []

[addresses]
perpetual = "0xbfc86b9b41633d8ee54f8b94c79f3b9e248c2eee57f01636116cc58b3fe57c37"

[dev-addresses]

[dependencies.Pyth]
local = "../vendor"

[dependencies.mock]
local = "../Mock"

#[dependencies.AptosFramework]
#git = "https://github.com/aptos-labs/aptos-core.git"
#rev = "mainnet"
#subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
