[package]
name = "perpetual"
version = "0.0.1"
authors = []

[addresses]
perpetual = "0x7fe5afe849218e50eabf21ecbd472803013607c17e97458d48d587f5cbc96b53"

[dev-addresses]

[dependencies.Pyth]
local = "../vendor"

[dependencies.mock]
local = "../Mock"

#[dependencies.AptosFramework]
#git = "https://github.com/aptos-labs/aptos-core.git"
#rev = "mainnet"
#subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
