[package]
name = "perpetual"
version = "0.0.1"
authors = []

[addresses]
perpetual = "0xd789e10dddb583e690e3341e6ce4c32c2c8ed39b84c78004e717f218c5f1c3d4"

[dev-addresses]

[dependencies.Pyth]
local = "../vendor"

#[dependencies.AptosFramework]
#git = "https://github.com/aptos-labs/aptos-core.git"
#rev = "mainnet"
#subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
