[package]
name = "perpetual"
version = "0.0.1"
authors = []

[addresses]
perpetual = "0x8d07663376c920257ab9f2bd8ef0cc5ed5f2264109a3d29fc2b6f8aafc5e875d"

[dev-addresses]

[dependencies.Pyth]
local = "../vendor"

#[dependencies.AptosFramework]
#git = "https://github.com/aptos-labs/aptos-core.git"
#rev = "mainnet"
#subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
