[package]
name = "perpetual"
version = "0.0.1"
authors = []

[addresses]
perpetual = "0x565904b9a3195938d5d94b892cfa384a4fa5489b7ea5315169226cfec158b44d"

[dev-addresses]

[dependencies.Pyth]
local = "../vendor"

[dependencies.mock]
local = "../Mock"

#[dependencies.AptosFramework]
#git = "https://github.com/aptos-labs/aptos-core.git"
#rev = "mainnet"
#subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
