[package]
name = "perpetual"
version = "0.0.1"
upgrade_policy = "compatible"
authors = []

[addresses]
perpetual = "0xdc7386d3e8a210b8edf5fabcd4c7baddaa29517269197e45146b02dea4cdbc2f"

[dev-addresses]

[dependencies.Pyth]
local = "../vendor/pyth"

[dependencies.Switchboard]
local = "../vendor/switchboard"

[dependencies.supra_holder]
local = "../vendor/supra"

[dependencies.amnis]
local = "../amnis"

[dependencies.mock]
local = "../Mock"

#[dependencies.AptosFramework]
#git = "https://github.com/aptos-labs/aptos-core.git"
#rev = "mainnet"
#subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
